name: React Native CI/CD

on:
  push:
    branches:
      - "**"

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: ğŸ“¦ Install dependencies
        run: |
          npm ci
          npm install -g firebase-tools

      - name: ğŸ”§ Setup Ruby & CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: |
          gem install cocoapods fastlane
          cd ios && pod install --repo-update && cd ..

      - name: ğŸ› ï¸ Build iOS Archive
        run: |
          cd ios
          xcodebuild -workspace cicdreactnative.xcworkspace \
            -scheme cicdreactnative \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $PWD/build/cicdreactnative.xcarchive

      - name: ğŸ“¦ Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath $PWD/build/cicdreactnative.xcarchive \
            -exportPath $PWD/build/ipa \
            -exportOptionsPlist ExportOptions.plist
          ls -R $PWD/build/ipa

      - name: ğŸ“¤ Upload to Firebase App Distribution
        run: |
          IPA_PATH=$(find ios/build/ipa -name "*.ipa" | head -n 1)
          firebase appdistribution:distribute "$IPA_PATH" \
            --app ${{ secrets.FIREBASE_APP_ID_IOS }} \
            --token ${{ secrets.FIREBASE_AUTH_TOKEN }} \
            --groups testers
