name: React Native CI/CD

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: |
          echo "ğŸ“¦ Installing dependencies..."
          npm install
          echo "âœ… Dependencies installed!"

      # Prettier check
      - name: Prettier check
        run: |
          echo "ğŸ“¦ Prettier checking..."
          npm run prettier:check
          echo "âœ… Prettier checked!"

      # ESLint check
      - name: ESLint check
        run: |
          echo "ğŸ“¦ ESLint checking..."
          npm run lint:fix
          echo "âœ… ESLint checked!"

      # Run tests
      - name: Test check
        run: |
          echo "ğŸ“¦ Test checking..."
          npm run test
          echo "âœ… Test checked!"

      # Run SonarCloud analysis
      - name: SonarCloud Scan
        run: |
          echo "ğŸ” Running SonarCloud scan..."
          npx sonar-scanner \
            -Dsonar.projectKey=sahil1608031 \
            -Dsonar.organization=sahil1608031 \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=de713e8f4069d29237a812c03b8b9debb27be138 \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          echo "âœ… SonarCloud scan completed!"
