name: React Native CI/CD

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "ðŸ“¦ Installing dependencies..."
          npm install
          echo "âœ… Dependencies installed!"

      - name: Prettier check
        run: |
           echo "ðŸ“¦ prettier checking..."
           npm run prettier:check
           echo "âœ… prettier checked!" 

      - name: Eslint check
        run: |
           echo "ðŸ“¦ Eslint checking..."
           npm run lint:fix
           echo "âœ… Eslint checked!"    
           
      - name: Test check
        run: |
           echo "ðŸ“¦ test checking..."
           npm run test
           echo "âœ… test checked!"     

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Android build check & upload
        run: |
          echo "ðŸ“¦ Building Android Debug APK..."
          cd android
          ./gradlew assembleDebug
          cd ..
          echo "âœ… Debug APK built!"
          
          echo "ðŸ“¤ Uploading to Firebase App Distribution..."
          firebase appdistribution:distribute android/app/build/outputs/apk/debug/app-debug.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "TESTERS_REELBOOK"
          echo "âœ… APK uploaded to Firebase App Distribution!"


        
